services:
  latlan_validate:
    class: AccessibilityBarriersBundle\Validator\Constraints\LatLanValidator
    tags:
      -  { name: validator.constraint_validator, alias: coordinates_validation }

  accessibility_barriers.serializer_nitification_coordinate:
    class: AccessibilityBarriersBundle\Serializer\NotificationCoordinateSubscribingHandler
    tags:
      - { name: jms_serializer.event_subscriber }

  accessibility_barriers.serializer_area_coordinate:
    class: AccessibilityBarriersBundle\Serializer\AreaCoordinateSubscribingHandler
    tags:
      - { name: jms_serializer.event_subscriber }

  accessibility_barriers.serializer_count_notifications:
    class: AccessibilityBarriersBundle\Serializer\CountNotificationsSubscribingHandler
    tags:
      - { name: jms_serializer.event_subscriber }