services:
  accessibility_barriers.serializer_coordinate:
    class: AccessibilityBarriersBundle\Serializer\CoordinateSubscribingHandler
    tags:
      - { name: jms_serializer.event_subscriber }

  latlan_validate:
    class: AccessibilityBarriersBundle\Validator\Constraints\LatLanValidator
    tags:
      -  { name: validator.constraint_validator, alias: coordinates_validation }