security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        oauth_token:
            pattern:    ^(/oauth/v2/token|/api/user/login)
            security:   false
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true # can be omitted as its default value
        admin:
            pattern:    ^/admin
            provider:   fos_userbundle
            form_login:
                provider:   fos_userbundle
                check_path: fsi_admin_security_user_check
                login_path: fsi_admin_security_user_login
                always_use_default_target_path: false
                default_target_path:            /admin/
            logout:
                path:   fsi_admin_security_user_logout
                target: fsi_admin_security_user_login
            anonymous:    ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
    role_hierarchy:
        ROLE_ADMIN: ROLE_API
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/issue, roles: [ ROLE_API ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }