AccessibilityBarriersBundle\Entity\Area:
    type: entity
    table: area
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            column: name
            type: string
            nullable: false
            length: 64
        latitude:
            column: latitude
            type: decimal
            scale: 8
            precision: 10
            nullable: false
        longitude:
            column: longitude
            type: decimal
            scale: 8
            precision: 11
            nullable: false
        distance:
            column: distance
            type: integer
            nullable: false

    manyToOne:
        user:
             targetEntity: OAuthBundle\Entity\User
             inversedBy: area
             joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true

    lifecycleCallbacks: {  }