AccessibilityBarriersBundle\Entity\Image:
    type: entity
    table: image
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            column: name
            type: string
            nullable: false
            length: 255

    lifecycleCallbacks: {  }