AccessibilityBarriersBundle\Entity\Image:
    type: entity
    table: image
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        original:
            column: original
            type: string
            nullable: false
            length: 255
        thumbnail:
            column: thumbnail
            type: string
            nullable: true
            length: 255
    manyToOne:
        notification:
            targetEntity: Notification
            inversedBy: images
            joinColumn:
                name: notification_id
                referencedColumnName: id

    lifecycleCallbacks: {  }