AccessibilityBarriersBundle\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:

  oneToMany:
    notifications:
      targetEntity: Notification
      mappedBy: user
    comments:
      targetEntity: Comment
      mappedBy: user
      cascade: ["all"]

  lifecycleCallbacks: {  }