OAuthBundle\Entity\AuthCode:
  type: entity
  table: authcode
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  manyToOne:
    client:
      targetEntity: OAuthBundle\Entity\Client
      joinColumn:
        nullable: false
    user:
        targetEntity: OAuthBundle\Entity\User

  lifecycleCallbacks: {  }
