AccessibilityBarriersBundle\Entity\Area:
  properties:
      name:
          - NotBlank: ~
          - Length:
             max:   64
      latitude:
          - NotBlank: ~
          - Length:
              max:   50
              max:   50
      longitude:
          - NotBlank: ~
          - Length:
              max:   50
      distance:
          - NotBlank: ~
          - Range:
              min: 0
              max: 5
  constraints:
      - AccessibilityBarriersBundle\Validator\Constraints\LatLan: ~