AccessibilityBarriersBundle\Entity\Comment:
    properties:
        content:
            - NotBlank: ~
            - Length:
                max:   200
        createdAt:
            - NotBlank: ~
            - DateTime: ~
        notification:
            - NotBlank: ~
        user:
            - NotBlank: ~