AccessibilityBarriersBundle\Entity\Subscribe:
  properties:
      email:
          - Email:
              message: The email "{{ value }}" is not a valid email.
              checkMX: false
  constraints:
      - AccessibilityBarriersBundle\Validator\Constraints\SubscribeUnique: ~