AccessibilityBarriersBundle\Entity\User:
  properties:
    startAt:
      - NotBlank: ~
      - DateTime: ~
    area:
      - NotBlank: ~
    category:
      - NotBlank: ~
    endAt:
      - DateTime: ~