AccessibilityBarriersBundle\Entity\Alert:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [ALERT_LIST]
    active:
      expose: false
      groups: [ALERT_LIST]
    createdAt:
      expose: false
      groups: [ALERT_LIST]
      type: DateTime<'Y-m-d'>
    message:
      expose: true
      groups: [ALERT_LIST]
    user:
      expose: false
      groups: [ALERT_LIST]
      type: OAuthBundle\Entity\User
    notification:
      expose: true
      groups: [ALERT_LIST]
      type: AccessibilityBarriersBundle\Entity\Notification

