AccessibilityBarriersBundle\Entity\User:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [USER_LIST, USER_DETAILS]
    notifications:
      expose: true
      groups: [USER_DETAILS]
      type: ArrayCollection<AccessibilityBarriersBundle\Entity\Notification>
      max_depth: 2
    comments:
      expose: true
      groups: [USER_DETAILS]
      type: ArrayCollection<AccessibilityBarriersBundle\Entity\Comment>
      max_depth: 2